image: ubuntu:bionic

variables:
  GRADLE_VERSION: "4.10.3"
  JDK14_FILENAME: "openjdk-14-jpackage+8_linux-x64_bin.tar.gz"
  JDK14_URL: "https://download.java.net/java/early_access/jpackage/8/$JDK14_FILENAME"
  BADASS_JLINK_JPACKAGE_HOME: "$CI_PROJECT_DIR/jdk-14"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - echo $BADASS_JLINK_JPACKAGE_HOME
  - echo $GRADLE_OPTS
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install openjdk-11-jdk gradle curl rpm fakeroot
  - curl --silent --show-error -O $JDK14_URL
  - tar xf $JDK14_FILENAME
  - $BADASS_JLINK_JPACKAGE_HOME/bin/jpackage --version
  - gradle wrapper --gradle-version=$GRADLE_VERSION --stacktrace

build:
  script:
    - java -version
    - ./gradlew build bitcoinj-walletfx-template:jpackage --stacktrace
  artifacts:
    paths:
      - bitcoinj-walletfx-template/build/jpackage
      - bitcoinj-walletfx-template/build/libs

