image: openjdk:11-jdk

before_script:
  - chmod +x ./gradlew

build:
  script:
    - java -version
    - LC_ALL=en_US.UTF-8 ./gradlew build
  artifacts:
    paths:
      - core/build
      - examples/build
      - tools/build
      - wallettemplate/build

