image: ubuntu:bionic

variables:
  GRADLE_VERSION: "5.6.2"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install openjdk-11-jdk gradle rpm fakeroot
  - gradle wrapper --gradle-version=$GRADLE_VERSION --stacktrace

build:
  script:
    - java -version
    - echo Gradle OPTS are $GRADLE_OPTS
    - ./gradlew -Ddownload.jpackage=true build bitcoinj-walletfx-template:jpackage --stacktrace
  artifacts:
    paths:
      - bitcoinj-walletfx-template/build/jpackage
      - bitcoinj-walletfx-template/build/libs

# Note: You can test changes to this file locally with:
# gitlab-runner exec docker --docker-privileged build

