image: ubuntu:bionic

variables:
  GRADLE_VERSION: "5.6"

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install openjdk-11-jdk gradle
  - gradle -c empty-settings.gradle wrapper --gradle-version=$GRADLE_VERSION --stacktrace

build:
  script:
    - java -version
    - ./gradlew build --stacktrace
