# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: bionic
language: java
matrix:
  include:
  - jdk: openjdk8
    env: GRADLE_VERSION=5.6
  - jdk: openjdk11
    env: GRADLE_VERSION=5.6
install: true
before_script:
  - gradle -c empty-settings.gradle wrapper --gradle-version=$GRADLE_VERSION
script:
  - ./gradlew clean build

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
